### ISSUE TITLE
Filters on the Product Def page

### ISSUE THREAD

**Issue by brianlash** [bynarlogic/pittsburgh_ammo#5]
Can  we add filters to the Product Def screen, so that (for instance) if we wanted to find all Hornady .22 LR products in 115 grain we could select each of those values from a series of dropdowns?

This will allay one of the fears I have for the data entry piece in which we end up with a lot of redundant products that aren't tied together appropriately with a common product ID. If you can create the filter function, the data entry coder's instruction for a given supplier will be to search the Product def table to find the product. If he can't locate it, only then should he create a new one.

This falls in line with my other suggestions... A nice to have, and certainly not a need to have. We can still require that the coder scour the Product Def screen for like products, and in a worst case scenario, we can do some of the cleanup ourselves.

If this is easy though, I think we should incorporate it.

**Comment by bynarlogic** [comment]
As discussed lets see if we can put together an excel report to spec out what is needed for the lookup table that would drive this feature.

**Comment by bynarlogic** [comment]
This feature has been deployed to production.
